In [29]:
import pandas as pd
import pymysql
import getpass

In [30]:
password = getpass.getpass()
conn = pymysql.connect(host='mysql.guaminsects.net',user='aubreymoore',passwd=password,db='oryctes')

········

In [31]:
sql = "SELECT trap_id, latitude, longitude FROM trap"
df = pd.io.sql.read_sql(sql, conn)
df

      trap_id   latitude   longitude
0     0002MAN  13.453480  144.792470
1        1480  13.406813  144.663096
2        1735  13.407382  144.663072
3        1763  13.409104  144.665649
4        1780  13.407810  144.663063
5        1806  13.408991  144.663185
6       AP001  13.477410  144.808240
7       AP002  13.476970  144.807330
8       AP003  13.476310  144.806180
9       AP004  13.475320  144.804050
10      AP005  13.474890  144.802730
11      AP006  13.474360  144.801640
12      AP007  13.473320  144.801670
13      AP008  13.471980  144.801560
14      AP009  13.470460  144.801130
15      AP010  13.470670  144.799850
16      AP011  13.471100  144.798680
17      AP012  13.471560  144.797450
18      AP013  13.472050  144.796460
19      AP014  13.472500  144.795010
20      AP015  13.473940  144.788890
21      AP016  13.491710  144.797759
22      AP017  13.491410  144.798070
23      AP018  13.492410  144.801100
24      AP019  13.500440  144.818700
25      AP020  13.499820  144.819700
26      AP021  13.497910  144.819870
27      AP022  13.493150  144.821460
28      AP023  13.492140  144.819050
29      AP024  13.490610  144.820560
...       ...        ...         ...
2237    x2018  13.380620  144.739850
2238    x2019  13.382840  144.743210
2239    x2020  13.384260  144.739850
2240    x2021  13.382530  144.739650
2241    x2022  13.374460  144.736070
2242    x2023  13.464170  144.703660
2243    x2024  13.466240  144.775670
2244    x2025  13.465620  144.775250
2245    x2026  13.462980  144.773710
2246    x2027  13.454170  144.760380
2247    x2028  13.453780  144.761920
2248    x2029  13.499650  144.777270
2249    x2030  13.498330  144.777820
2250    x2031  13.468150  144.777390
2251    x3000  13.339820  144.741120
2252   x3000W  13.525150  144.869820
2253   x3001W  13.525710  144.871470
2254   X815TR  13.433580  144.786350
2255    x9989  13.356600  144.648830
2256    x9990  13.355380  144.648760
2257    x9991  13.353450  144.651110
2258    x9992  13.446640  144.751270
2259    x9993  13.447750  144.748540
2260    x9994  13.451240  144.745530
2261    x9995  13.446730  144.748810
2262    x9996  13.320650  144.847320
2263   x9996a  13.320870  144.736210
2264    x9997  13.319430  144.737150
2265    X9998  13.505340  144.801650
2266    X9999  13.512230  144.807190

[2267 rows x 3 columns]

In [35]:
df1 = df.groupby(['latitude','longitude']).filter(lambda df:df.shape[0] > 1)
df1.sort('latitude')

      trap_id  latitude  longitude
498     X0125  13.44046  144.74878
171   SPCORD1  13.44046  144.74878
555     x0186  13.44093  144.75191
172   SPCORD2  13.44093  144.75191
2009   x1686B  13.46444  144.84021
208    T0012B  13.46444  144.84021
78      AP072  13.49385  144.80342
79     AP072a  13.49385  144.80342
76      AP071  13.49425  144.80420
77     AP071a  13.49425  144.80420
879     X0532  13.49804  144.79643
407     X0036  13.49804  144.79643
192   SPCP030  13.49856  144.79489
401     X0030  13.49856  144.79489
1892    X1546  13.49962  144.77336
1707   X1340a  13.49962  144.77336
180   SPCP009  13.50143  144.79333
379     X0009  13.50143  144.79333
181   SPCP010  13.50150  144.79063
380     X0010  13.50150  144.79063
378     X0008  13.50181  144.78851
179   SPCP008  13.50181  144.78851
382     X0012  13.50237  144.79350
183   SPCP012  13.50237  144.79350
383     X0013  13.50311  144.79638
162   SPC0013  13.50311  144.79638
377     X0007  13.50386  144.78938
178   SPCP007  13.50386  144.78938
381     X0011  13.50434  144.79183
182   SPCP011  13.50434  144.79183
...       ...       ...        ...
168   SPC0027  13.51056  144.80529
169   SPC0028  13.51106  144.80609
398     X0028  13.51106  144.80609
1217   X0864a  13.51385  144.80458
1194    x0844  13.51385  144.80458
1713    X1346  13.52176  144.81479
1429    X1070  13.52176  144.81479
1386    X1028  13.52176  144.81479
1478    X1123  13.52227  144.81615
1481    X1125  13.52227  144.81615
1355    X0998  13.52329  144.81290
1356   X0998a  13.52329  144.81290
399     X0029  13.52548  144.80970
170   SPC0029  13.52548  144.80970
157   SPC0001  13.52714  144.80374
358   X0001FF  13.52714  144.80374
911    x0562a  13.52727  144.81299
577     X0210  13.52727  144.81299
158   SPC0002  13.52805  144.80362
363   X0002FF  13.52805  144.80362
368   X0003FF  13.52942  144.80370
159   SPC0003  13.52942  144.80370
160   SPC0004  13.53016  144.80334
372   X0004FF  13.53016  144.80334
288     T0082  13.55560  144.83580
343     T0144  13.55560  144.83580
1814    x1457  13.63256  144.84349
284     T0078  13.63256  144.84349
205     T0010  13.64055  144.85368
211     T0015  13.64055  144.85368

[105 rows x 3 columns]

In [27]:
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.random.randint(5,size=(6,4)),index=dates,columns=list('ABCD'))
df

            A  B  C  D
2013-01-01  0  0  3  1
2013-01-02  0  2  2  2
2013-01-03  4  3  2  0
2013-01-04  1  1  2  0
2013-01-05  4  0  4  2
2013-01-06  4  0  0  1

In [28]:
df.groupby(['A','B']).filter(lambda df:df.shape[0] > 1)

            A  B  C  D
2013-01-05  4  0  4  2
2013-01-06  4  0  0  1

df.groupby([...]).filter(lambda df:df.shape[0] > 1)